import { NextResponse } from 'next/server';
import { getSupabaseAdminClient, isSupabaseConfigured } from '@/lib/supabase';

export const dynamic = 'force-dynamic';

interface VerifyOrderItem {
  productId: string;
  variantId?: string;
  name: string;
  variantName?: string;
  price: number;
  quantity: number;
  image: string;
}

interface VerifyOrderData {
  customer_name: string;
  email: string;
  customer_phone: string;
  shipping_address: string;
  items: VerifyOrderItem[];
  subtotal?: number;
  delivery_fee?: number;
  total_price: number;
}

interface VerifyRequestBody {
  reference: string;
  orderData: VerifyOrderData;
}

function isValidPaystackReference(ref: unknown): boolean {
  if (typeof ref !== 'string' || !ref.trim()) return false;
  // Format generated by Jirel Kitchen Hub: JK_${timestamp}_${random} or standard alphanumeric references
  return /^JK_\d+_[a-zA-Z0-9]+$/i.test(ref) || /^[a-zA-Z0-9_-]{6,100}$/.test(ref);
}

function isSimulationMode(reference: string): boolean {
  const secretKey = process.env.PAYSTACK_SECRET_KEY;
  const isPlaceholderKey =
    !secretKey ||
    secretKey.includes('placeholder') ||
    secretKey.includes('your_secret_key') ||
    secretKey.trim() === '';

  // In production with a real configured key, simulation is strictly disallowed
  if (!isPlaceholderKey && process.env.NODE_ENV === 'production') {
    return false;
  }

  const isMockRef =
    reference.startsWith('sim_') ||
    reference.startsWith('mock_') ||
    reference.includes('_mock_');
  return isPlaceholderKey || (isMockRef && process.env.NODE_ENV !== 'production');
}

export async function POST(request: Request) {
  try {
    let body: VerifyRequestBody;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { success: false, error: 'Invalid JSON request payload' },
        { status: 400 }
      );
    }

    if (!body || typeof body !== 'object') {
      return NextResponse.json(
        { success: false, error: 'Request body must be an object' },
        { status: 400 }
      );
    }

    const { reference, orderData } = body;

    // 1. Reference validation
    if (!reference || typeof reference !== 'string' || !reference.trim()) {
      return NextResponse.json(
        { success: false, error: 'Valid Paystack reference is required' },
        { status: 400 }
      );
    }

    if (!isValidPaystackReference(reference)) {
      return NextResponse.json(
        { success: false, error: 'Invalid Paystack reference format' },
        { status: 400 }
      );
    }

    // 2. OrderData validation
    if (!orderData || typeof orderData !== 'object') {
      return NextResponse.json(
        { success: false, error: 'orderData is required' },
        { status: 400 }
      );
    }

    if (
      !orderData.customer_name ||
      typeof orderData.customer_name !== 'string' ||
      !orderData.customer_name.trim()
    ) {
      return NextResponse.json(
        { success: false, error: 'Customer name is required' },
        { status: 400 }
      );
    }

    if (
      !orderData.email ||
      typeof orderData.email !== 'string' ||
      !orderData.email.includes('@')
    ) {
      return NextResponse.json(
        { success: false, error: 'Valid email address is required' },
        { status: 400 }
      );
    }

    if (
      !orderData.customer_phone ||
      typeof orderData.customer_phone !== 'string' ||
      orderData.customer_phone.trim().length < 7
    ) {
      return NextResponse.json(
        { success: false, error: 'Valid customer phone number is required (min 7 digits)' },
        { status: 400 }
      );
    }

    if (
      !orderData.shipping_address ||
      typeof orderData.shipping_address !== 'string' ||
      !orderData.shipping_address.trim()
    ) {
      return NextResponse.json(
        { success: false, error: 'Shipping address is required' },
        { status: 400 }
      );
    }

    if (!Array.isArray(orderData.items) || orderData.items.length === 0) {
      return NextResponse.json(
        { success: false, error: 'Order must contain at least one item' },
        { status: 400 }
      );
    }

    if (
      typeof orderData.total_price !== 'number' ||
      orderData.total_price <= 0 ||
      isNaN(orderData.total_price)
    ) {
      return NextResponse.json(
        { success: false, error: 'Total price must be a positive number' },
        { status: 400 }
      );
    }

    // 3. Price anti-tamper check
    const itemsSubtotal = orderData.items.reduce(
      (sum, item) => sum + item.price * item.quantity,
      0
    );
    const expectedTotal = itemsSubtotal + (orderData.delivery_fee || 0);
    if (Math.abs(expectedTotal - orderData.total_price) > 0.01) {
      return NextResponse.json(
        { success: false, error: 'Total price does not match sum of items' },
        { status: 400 }
      );
    }

    const expectedKobo = Math.round(orderData.total_price * 100);

    // 4. Paystack Verification / Simulation
    let paystackPaymentDetails: Record<string, unknown> = {};

    if (isSimulationMode(reference)) {
      paystackPaymentDetails = {
        id: Math.floor(Math.random() * 100000000),
        status: 'success',
        reference,
        amount: expectedKobo,
        currency: 'NGN',
        paid_at: new Date().toISOString(),
        channel: 'simulated_card',
        gateway_response: 'Simulated Approval',
      };
    } else {
      const secretKey = process.env.PAYSTACK_SECRET_KEY!;
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000);

      try {
        const verifyUrl = `https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`;
        const paystackRes = await fetch(verifyUrl, {
          method: 'GET',
          headers: {
            Authorization: `Bearer ${secretKey}`,
            'Content-Type': 'application/json',
          },
          signal: controller.signal,
        });

        clearTimeout(timeoutId);

        if (!paystackRes.ok) {
          if (paystackRes.status === 404) {
            return NextResponse.json(
              { success: false, error: 'Transaction reference not found on payment gateway' },
              { status: 404 }
            );
          }
          return NextResponse.json(
            { success: false, error: `Payment gateway error (${paystackRes.status})` },
            { status: 502 }
          );
        }

        const paystackJson = await paystackRes.json();

        if (!paystackJson.status || !paystackJson.data) {
          return NextResponse.json(
            { success: false, error: paystackJson.message || 'Payment verification failed' },
            { status: 400 }
          );
        }

        const data = paystackJson.data;

        // Security assertion 1: status
        if (data.status !== 'success') {
          return NextResponse.json(
            { success: false, error: `Payment status is ${data.status}: payment was not completed` },
            { status: 400 }
          );
        }

        // Security assertion 2: currency
        if (data.currency !== 'NGN') {
          return NextResponse.json(
            { success: false, error: `Payment currency mismatch: expected NGN, received ${data.currency}` },
            { status: 400 }
          );
        }

        // Security assertion 3: strict kobo amount match
        if (data.amount !== expectedKobo) {
          return NextResponse.json(
            {
              success: false,
              error: `Payment amount mismatch: expected ${expectedKobo} kobo, received ${data.amount} kobo`,
            },
            { status: 400 }
          );
        }

        paystackPaymentDetails = data;
      } catch (fetchErr: unknown) {
        clearTimeout(timeoutId);
        const err = fetchErr as Error;
        if (err?.name === 'AbortError') {
          return NextResponse.json(
            { success: false, error: 'Payment gateway timeout during verification' },
            { status: 504 }
          );
        }
        return NextResponse.json(
          { success: false, error: 'Failed to communicate with payment gateway' },
          { status: 502 }
        );
      }
    }

    // 5. Supabase Order Mutation
    const adminSupabase = getSupabaseAdminClient();

    if (adminSupabase && isSupabaseConfigured()) {
      const { data: order, error: dbError } = await adminSupabase
        .from('orders')
        .upsert(
          {
            customer_name: orderData.customer_name.trim(),
            email: orderData.email.trim().toLowerCase(),
            customer_phone: orderData.customer_phone.trim(),
            shipping_address: orderData.shipping_address.trim(),
            items: orderData.items,
            subtotal: orderData.subtotal ?? itemsSubtotal,
            delivery_fee: orderData.delivery_fee ?? 0,
            total_price: orderData.total_price,
            currency: 'NGN',
            paystack_reference: reference,
            payment_status: 'paid',
            paid_at: paystackPaymentDetails.paid_at || new Date().toISOString(),
            metadata: {
              paystack: paystackPaymentDetails,
              verified_at: new Date().toISOString(),
            },
          },
          {
            onConflict: 'paystack_reference',
          }
        )
        .select()
        .single();

      if (dbError) {
        console.error('[Verify] Database order write error:', dbError);
        return NextResponse.json(
          { success: false, error: 'Failed to record confirmed order in database' },
          { status: 500 }
        );
      }

      return NextResponse.json({
        success: true,
        message: 'Payment verified and order confirmed',
        order: {
          ...order,
          status: order.payment_status || 'paid',
          payment_status: order.payment_status || 'paid',
        },
      });
    }

    // 6. Resilient Fallback (When Supabase is in placeholder/mock mode)
    const mockOrder = {
      id: `ord-mock-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      order_number: `JK-${Math.floor(100000 + Math.random() * 900000)}`,
      paystack_reference: reference,
      customer_name: orderData.customer_name,
      email: orderData.email,
      customer_phone: orderData.customer_phone,
      shipping_address: orderData.shipping_address,
      items: orderData.items,
      subtotal: orderData.subtotal ?? itemsSubtotal,
      delivery_fee: orderData.delivery_fee ?? 0,
      total_price: orderData.total_price,
      currency: 'NGN',
      status: 'paid' as const,
      payment_status: 'paid' as const,
      paid_at: new Date().toISOString(),
      created_at: new Date().toISOString(),
    };

    return NextResponse.json({
      success: true,
      message: 'Payment verified and order confirmed',
      order: mockOrder,
    });
  } catch (error: unknown) {
    console.error('[Verify] Unexpected internal error:', error);
    return NextResponse.json(
      { success: false, error: 'Internal server error during verification' },
      { status: 500 }
    );
  }
}
